name = "pastebin"
compatibility_date = "2023-01-28"

account_id = "889b0f40a1aff61027b26a2ffe73a435"
workers_dev = false
main = "src/index.js"

# config for default production environment
vars = { ENVIRONMENT = "production" }
route = { pattern = "pastebin.717717.cloudns.biz", custom_domain = true }
kv_namespaces = [
  { binding = "pastebin", id = "89212d2f1fc640aa840d8ac29810728a" },
]

#[env.preview]
#vars = { ENVIRONMENT = "preview" }
#route = { pattern = "pb-preview.shz.al", custom_domain = true }
#minify = false

kv_namespaces = [
  { binding = "pastebin", id = "89212d2f1fc640aa840d8ac29810728a" }
]

